import Head from 'next/head'
import Header from '../components/Home/Header/Header/Header'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Clothing Wholesale</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
      </main>
    </div>
  )
}
