import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h2 className='text-center font-bold uppercase text-indigo-200'>let start creating wholesale</h2>
      </main>
    </div>
  )
}
